language: python
python:
  - 2.7
  - 3.3
  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libatlas-base-dev
      - gfortran
      - gcc-4.9
      - g++-4.9
env:
    - CC=gcc-4.9 CXX=g++-4.9
before_install:
 - mkdir -p $HOME/.cache/pip/wheels
 # build wheel only if none present
 - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels cython
 - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels numpy
 - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels scipy
 - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels pandas
 # now install from it
 - pip install --no-index --find-links=$HOME/.cache/pip/wheels numpy
 - pip install --no-index --find-links=$HOME/.cache/pip/wheels cython
 - pip install --no-index --find-links=$HOME/.cache/pip/wheels scipy
 - pip install --no-index --find-links=$HOME/.cache/pip/wheels pandas
 - pip install git+git://github.com/jeremymcrae/denovonear.git
install:
  - python setup.py install
  - pip install coveralls
script:
  - python setup.py test
  - python -m coverage run --source=./fitDNM -m unittest discover
after_success:
  - coveralls
