language: python
python:
  - 2.7
  - 3.4
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libatlas-base-dev
      - gfortran
      - gcc-4.9
      - g++-4.9
env:
    - CC=gcc-4.9 CXX=g++-4.9
before_install:
 - pip install --upgrade pip setuptools wheel
 - pip install --only-binary=all numpy scipy cython pandas
 - pip install git+git://github.com/jeremymcrae/denovonear.git
install:
  - python setup.py install
  - pip install coveralls
script:
  - python setup.py test
  - python -m coverage run --source=./fitDNM -m unittest discover
after_success:
  - coveralls
